stages:
  build_dataset:
    cmd: python ./Convert_To_Procedures/convert_to_procedures.py
    deps:
    - ./sql/00_REF.sql
  prepare_dataset:
    cmd: python ./src/API_DATA_GENERATION.py
    params:
    - prepare.MODEL_TYPE
    - prepare.TEST_SET_LENGTH
    outs:
    - ./data/API_dataset.pkl
